In [1]:
from joblib import load

In [2]:
clf = load('0-RFor_Unce.joblib')

In [3]:
clf.predict([[1,2,3,4]])

ValueError: X has 4 features, but DecisionTreeClassifier is expecting 66 features as input.

In [13]:
from joblib import load
import glob
import numpy as np
import os
classifiers = []

committee_dir = "../../models/1-RFor_Unce_AdaB_Unce_GBTr_Unce-25-83-20210707_12:14:45"

print(os.path.isdir(committee_dir))

some_new_data = np.random.rand(100,66)

classifiers = {} # Dictionary to hold all the individual classifiers in the committee
for i, filename in enumerate(glob.iglob(f"{committee_dir}/*.joblib")):
    
    # This is only required if you are using a scalar during training
    if "SCALER" in filename:
        continue

    classifiers[f"{i}"] = load(filename)

for i, clf in enumerate(classifiers):
    pred_clf = classifiers[clf].predict_proba(some_new_data)
    if i == 0:
        predictions_total = pred_clf
    else:
        predictions_total = predictions_total + pred_clf

predictions_avg = predictions_total / len(classifiers.keys()) # This is the averaged probabilities for each class
predictions = np.argmax(predictions_avg, axis=1) # This is the final prediction made

print(predictions)

True
skipping...
[0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1
 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0
 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 1]


In [11]:
scaler = load("models/your_classifier_model-SCALER.joblib")

some_new_data = np.random.rand(100,66)

new_data_scaled = scaler.transform(some_new_data)

[[0.24897113 0.29826167 0.90544499 0.63188886 0.25490164]
 [0.55943828 0.86329588 0.690943   0.1826501  0.04286961]
 [0.39702657 0.62118617 0.77466184 0.70162332 0.57193225]
 [0.90071488 0.11927548 0.21550119 0.18858307 0.43747716]
 [0.23751002 0.90805116 0.13110091 0.95688561 0.39043904]]
[[-4.83873821 -4.51905195 -4.81259348 -5.21814428 -5.57432286]
 [-4.76505062 -4.38674233 -4.86921706 -5.34706529 -5.63838385]
 [-4.80359811 -4.44343526 -4.84711722 -5.19813213 -5.47853875]
 [-4.68405058 -4.56096374 -4.99472276 -5.34536267 -5.51916152]
 [-4.84145844 -4.37626233 -5.01700249 -5.12487782 -5.53337309]]
